# Generated by Django 4.1.3 on 2022-12-07 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irasas',
            options={'verbose_name': 'Įrašas', 'verbose_name_plural': 'Įrašai'},
        ),
        migrations.AddField(
            model_name='irasas',
            name='atnaujinta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='irasas',
            name='sukurta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irasas',
            name='kategorija',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='irasas',
            name='tekstas',
            field=models.TextField(),
        ),
    ]
